image: maven:3.6.2-jdk-8
stages:
  - suite-funcional-web

siebel-dev:
  stage: suite-funcional-web
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=SuiteSiebelWeb.xml -Denv=hom
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html
