stages:
  - suite-funcional-web

siebel-dev:
  before_script:
  - docker kill $(docker ps -q)
  - sh grid/start-zalenium.sh
  stage: suite-funcional-web
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=SuiteSiebelWeb.xml -Denv=hom
  tags:
    - docker-images-cds
  after_script:
    - sh grid/stop-zalenium.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html
