stages:
  - healthcheck
  - contract
  - Resumo
  - Digital

healthcheck:
  stage: healthcheck
  script:
    - mvn clean test -Dtest=*HealthcheckTest
  tags:
    - docker-images-cds

contract:
  stage: contract
  when: always
  script:
    - mvn clean test -Dtest=*ContractTest
  tags:
    - docker-images-cds
  artifacts:
    when: always
    expire_in: 1 week

resumo:
  before_script:
  - sh grid/start-zalenium.sh
  stage: Resumo
  when: always
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=SuiteResumo.xml -Denv=ci
  tags:
    - docker-images-cds
  after_script:
    - sh grid/stop-zalenium.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html

digital:
  before_script:
    - sh grid/start-zalenium.sh
  stage: Digital
  when: always
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=SuiteDigital.xml -Denv=ci
  tags:
    - docker-images-cds
  after_script:
    - sh grid/stop-zalenium.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html
