stages:
  - suite-funcional-web

siebel-dev:
  stage: suite-funcional-web
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=SuiteSiebelWeb.xml -Denv=hom -X
  tags:
    - docker-images-cds
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html
