stages:

  - Negocio
default:
  image: harbor.sicredi.net/docker-base-images/maven:3.6.3-jdk-8-slim


Negocio:
  services:
    - selenium/standalone-chrome
  stage: Negocio
  when: always
  script:
    - mvn clean test -PsuiteFuncional -DtestSuite=Negocio.xml -Denv=ci
  tags:
    - autoscaling_uat
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/relatorio/*.html